#!/bin/bash

TARGET=$1
FOUND_LAYOUT=$(lsblk -ln | grep $TARGET | tr -s ' ')

echo "# The following was generated by genfstab.sh" > fstab.gen
echo "# Modify or use at your own risk" >> fstab.gen
echo "" >> fstab.gen


IFS=$'\n'

for DISK_LINE in $FOUND_LAYOUT
do

	# Could all be done with one sed but am to lazy to rewrite this shit 
	DISK_PATH=/dev/$(echo $DISK_LINE | cut -d ' ' -f1)
	BLK_LINE=$(blkid $DISK_PATH)
	UUID=$(echo $BLK_LINE | cut -d ' ' -f2)
	MOUNT=$(echo $DISK_LINE | cut -d ' ' -f7)
	if [ $MOUNT = $TARGET ]
	then
		MPOINT=/
		MOPTS=noatime
		DUMP=0
		PASS=1

	else
		
		MPOINT=${MOUNT:$(($(echo $TARGET| wc -c) - 1))}
		MOPTS=defaults
		if [ $MPOINT = "/boot" ]
		then
			DUMP=1
			PASS=2
		else
			DUMP=0
			PASS=0
		fi


	fi
	FS_TYPE=$(echo $BLK_LINE | cut -d ' ' -f4 | sed 's/[^"]*"\([^"]*\).*/\1/')


	echo "#$DISK_PATH" >> fstab.gen
	echo "$UUID $MPOINT $FS_TYPE $MOPTS $DUMP $PASS" >> fstab.gen
done

